[package]
name = "teaclave_service_enclave_utils"
version = "0.1.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave enclave utils"
license = "Apache-2.0"
edition = "2018"

[features]
default = []
mesalock_sgx = [
    "sgx_tstd",
    "teaclave_service_config/mesalock_sgx",
]
cov = ["sgx_cov"]

[dependencies]
anyhow     = { version = "1.0.26" }
env_logger = { version = "0.7.1" }
log        = { version = "0.4.6" }

teaclave_service_config                   = { path = "../service_config" }
teaclave_service_enclave_utils_proc_macro = { path = "./proc_macro" }

sgx_cov  = { version = "1.1.0", optional = true }
sgx_tstd = { version = "1.1.0", features = ["net", "backtrace"], optional = true }
