[package]
name = "teaclave_types"
version = "0.1.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave types"
license = "Apache-2.0"
edition = "2018"

[features]
default = []
mesalock_sgx = ["sgx_tstd"]

[dependencies]
anyhow       = { version = "1.0.26" }
sgx_types    = { version = "1.1.0" }
hex          = { version = "0.4.0" }
serde        = { version = "1.0.92" }
serde_derive = { version = "1.0.92" }
toml         = { version = "0.5.3" }
ring         = { version = "0.16.5" }
thiserror    = { version = "1.0.9" }

sgx_tstd = { version = "1.1.0", features = ["net", "backtrace"], optional = true }