[package]
name = "enclave_unit_test_enclave"
version = "0.1.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Enclave Unit Test"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "enclave_unit_test_enclave"
crate-type = ["staticlib"]

[features]
default = []
mesalock_sgx = [
  "sgx_tstd",
  "teaclave_attestation/mesalock_sgx",
  "teaclave_ipc/mesalock_sgx",
  "teaclave_rpc/mesalock_sgx",
  "teaclave_service_config/mesalock_sgx",
  "teaclave_service_enclave_utils/mesalock_sgx",
  "teaclave_types/mesalock_sgx",
  "teaclave_frontend_service_enclave/mesalock_sgx",
  "teaclave_frontend_service_enclave/enclave_unit_test"
]
cov = ["sgx_cov"]

[dependencies]
log         = { version = "0.4.6" }
anyhow      = { version = "1.0.26" }
serde       = { version = "1.0.92" }
thiserror   = { version = "1.0.9" }

teaclave_attestation           = { path = "../../../attestation" }
teaclave_config                = { path = "../../../config" }
teaclave_ipc                   = { path = "../../../ipc" }
teaclave_rpc                   = { path = "../../../rpc" }
teaclave_service_config        = { path = "../../../utils/service_config" }
teaclave_service_enclave_utils = { path = "../../../utils/service_enclave_utils" }
teaclave_types                 = { path = "../../../types" }

teaclave_frontend_service_enclave      = { path = "../../../services/frontend/enclave" }

sgx_cov   = { version = "1.1.0", optional = true }
sgx_tstd  = { version = "1.1.0", features = ["net", "thread", "backtrace"], optional = true }
sgx_types = { version = "1.1.0" }
