[package]
name = "private_join_and_compute"
version = "0.1.0"
authors = ["MesaTEE Authors <developers@mesatee.org>"]
description = "Multi-party private join and compute task with MesaTEE."
license = "Apache-2.0"
edition = "2018"

[dependencies]
mesatee_sdk = { path = "../../mesatee_sdk" }
lazy_static = "1.1.0"
