# Teaclave Build Config

# Intel Attestation Service root CA certificate to verify attestation report
ias_root_ca_cert = { path = "../keys/ias_root_ca_cert.pem" }

# Auditors' public keys to verify their endorsement signatures
auditor_public_keys = [
    { path = "../keys/auditors/godzilla/godzilla.public.pem" },
    { path = "../keys/auditors/optimus_prime/optimus_prime.public.pem" },
    { path = "../keys/auditors/albus_dumbledore/albus_dumbledore.public.pem"},
]

# RPC max message size
rpc_max_message_size = 409600

# Specify accepted inbound services to enforce incoming connections via mutual attestation
[inbound]
access_control = ["teaclave_management_service"]
authentication = ["teaclave_frontend_service"]
storage = ["teaclave_frontend_service", "teaclave_management_service"]
management = ["teaclave_frontend_service"]
