[package]
name = "teaclave_config"
version = "0.1.0"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Build and runtime configurations."
license = "Apache-2.0"
edition = "2018"

[features]
default = []
mesalock_sgx = ["sgx_tstd"]

[dependencies]
anyhow = { version = "1.0.26" }
serde  = { version = "1.0.92", features = ["derive"] }
toml   = { version = "0.5.1" }

sgx_tstd = { version = "1.1.0", optional = true }
